// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.DBContext;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230225205355_q")]
    partial class q
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.DBContext.CV_upload", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.ToTable("CV_uploads");
                });

            modelBuilder.Entity("WebApplication3.DBContext.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Job_postId")
                        .HasColumnType("int");

                    b.Property<int>("User_idComment")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("User_idComment");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebApplication3.DBContext.Company", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("WebApplication3.DBContext.CompanyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Company_idAccount")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("about")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("about");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("address");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Company_idAccount");

                    b.ToTable("CompanyAccounts");
                });

            modelBuilder.Entity("WebApplication3.DBContext.Cv_Creat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("AboutMe");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYear")
                        .HasColumnType("int");

                    b.Property<int>("Gpa")
                        .HasColumnType("int");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("Skills");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_idCv_Creat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_idCv_Creat");

                    b.ToTable("Cv_Creats");
                });

            modelBuilder.Entity("WebApplication3.DBContext.Jobs_Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Job_Deadline")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pre_title")
                        .IsRequired()
                        .HasColumnType("Varchar(200)")
                        .HasColumnName("Pre_title");

                    b.Property<string>("Requrment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("Varchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Jobs_Posts");
                });

            modelBuilder.Entity("WebApplication3.DBContext.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("Varchar(Max)")
                        .HasColumnName("First_Name");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("Varchar(200)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication3.DBContext.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Gpa")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_idAccount")
                        .HasColumnType("int");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("bio");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("city");

                    b.Property<int>("cv_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User_idAccount");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("WebApplication3.DBContext.image_post", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("image_file")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("image_file");

                    b.Property<string>("image_name")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("image_name");

                    b.Property<string>("image_type")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("image_type");

                    b.HasKey("id");

                    b.ToTable("image_posts");
                });

            modelBuilder.Entity("WebApplication3.DBContext.notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("User_idnotifications")
                        .HasColumnType("int");

                    b.Property<string>("notificat_text")
                        .IsRequired()
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("notificat_text");

                    b.HasKey("Id");

                    b.HasIndex("User_idnotifications");

                    b.ToTable("notificationss");
                });

            modelBuilder.Entity("WebApplication3.DBContext.Comment", b =>
                {
                    b.HasOne("WebApplication3.DBContext.User", "user")
                        .WithMany()
                        .HasForeignKey("User_idComment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("WebApplication3.DBContext.CompanyAccount", b =>
                {
                    b.HasOne("WebApplication3.DBContext.User", "Company")
                        .WithMany()
                        .HasForeignKey("Company_idAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebApplication3.DBContext.Cv_Creat", b =>
                {
                    b.HasOne("WebApplication3.DBContext.User", "user")
                        .WithMany()
                        .HasForeignKey("User_idCv_Creat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("WebApplication3.DBContext.UserAccount", b =>
                {
                    b.HasOne("WebApplication3.DBContext.User", "user")
                        .WithMany()
                        .HasForeignKey("User_idAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("WebApplication3.DBContext.notifications", b =>
                {
                    b.HasOne("WebApplication3.DBContext.User", "user")
                        .WithMany()
                        .HasForeignKey("User_idnotifications")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
